name: smartbites
description: "Application de gestion d'une liste de course et de partage de recettes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  timezone: ^0.10.1
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  marquee: ^2.3.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.4
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0  # Simplifie le code
  freezed_annotation: ^3.1.0   # ModÃ¨les solides
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ressources/logo_App.png"
flutter:
  generate: true
  uses-material-design: true

  assets:
    - /lib/old/ressources/
    #- lib/ressources/nova/
    #- lib/ressources/nutriscore/
l10n:
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  arb-dir: lib/l10n
