name: SmartBites
description: "SAE Food Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  timezone: ^0.10.1
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  marquee: ^2.2.3


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ressources/logo_App.png"
flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/ressources/
    - lib/ressources/nova/
    - lib/ressources/nutriscore/
l10n:
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  arb-dir: lib/l10n
